framework:
  exceptions:
    Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException:
      log_level: 'debug'
      status_code: 400
    Symfony\Component\Serializer\Exception\NotEncodableValueException:
      log_level: 'debug'
      status_code: 400
    Symfony\Component\Serializer\Exception\NotNormalizableValueException:
      log_level: 'debug'
      status_code: 400
    SymfonyCasts\Bundle\ResetPassword\Exception\ResetPasswordExceptionInterface:
      log_level: 'debug'
      status_code: 400
