framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'

when@test:
    framework:
        mailer:
            message_bus: false
            envelope:
                recipients: ['test.email@mtec.by']
