pentatrion_vite:
  public_directory: /public
  build_directory: /build/
  throw_on_missing_entry: true
  proxy_origin: https://host.docker.internal:5173

  script_attributes:
    

  link_attributes:

when@prod:
  pentatrion_vite:
    cache: true
