pentatrion_vite:
  # path to the web root relative to the Symfony project root directory
  public_dir: /public

  # Base public path when served in development or production
  base: /build/

  # you can set different origin for asset proxy for vite dev
  # required when vite dev is running outside Docker container
  # on your host machine, eg. http://host.docker.internal:5173
  proxy_origin: https://host.docker.internal:5173

  script_attributes:
    # you can define your attributes that you want to apply
    # for all your script tags

  link_attributes:
    # you can define your attributes that you want to apply
    # for all your link tags

  # only if you have multiple vite.config files
  # leave keys : base, script_attributes, link_attributes empty
  # and fill in the following
  # default_build: <custom-build-name-1>
  # builds:
  #     <custom-build-name-1>:
  #         # Base public path when served in development or production
  #         base: /build1/

  #         script_attributes:
  #             # etc

  #         link_attributes:
  #             # etc
