name: CI

on:
  push:
  pull_request:

jobs:
  php-lint:
    name: Lint the the code
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Composer
        uses: php-actions/composer@v6
        with:
          php_version: "8.2.6"
          php_extensions: amqp
          version: 2.x

      - name: Format the PHP code with php-cs-fixer
        run: composer run php-cs-fixer

      - name: Format the PHP code with php-cs-fixer
        run: composer run rector

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm ci

      - name: Format the Vue code
        run: npm run format

      - name: Lint the Vue code with eslint
        run: npm run lint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Github Actions] Lint the code"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull images
        run: docker compose pull

      - name: Start services
        run: docker compose -f docker-compose.yml up --build -d

      - name: Wait for services
        run: |
          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker compose ps -q php)")"; do
            case $status in
              starting) sleep 1;;
              healthy) exit 0;;
              unhealthy) exit 1;;
            esac
          done
          exit 0

      - name: Check HTTP reachability
        run: curl http://localhost

      - name: Check HTTPS reachability
        run: curl -k https://localhost
